language: node_js
cache: yarn
node_js:
- "node"
- "lts/*"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn test
